apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo-app
  labels:
    app: devsecops-demo-app
spec:
  type: ClusterIP
  selector:
    app: devsecops-demo-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
